stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  KUBE_NAMESPACE: "murashov-1"
  IMAGE_PULL_SECRET_NAME: murashov-secret

docker-build-push:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_TAG
  when: manual


deploy:
  stage: deploy
  image:
    name: dtzar/helm-kubectl:3.13
    entrypoint: [""]
  script:
    - mkdir -p $HOME/.kube
    - echo $KUBECONFIG | base64 -d > $HOME/.kube/config
    - export KUBECONFIG=$HOME/.kube/config
    - kubectl config set-context --current --namespace=$KUBE_NAMESPACE
    - kubectl get secret ${IMAGE_PULL_SECRET_NAME} || kubectl create secret docker-registry ${IMAGE_PULL_SECRET_NAME} --docker-server=${CI_REGISTRY} --docker-username=${CI_REGISTRY_USER} --docker-password=${CI_REGISTRY_PASSWORD}
    - helm upgrade --install myhelm ./helm --set image.repository=$CI_REGISTRY --set image.tag=$CI_COMMIT_REF_SLUG --recreate-pods
  
  only:
    - main
 