replicaCount: 1
namespace: murashov-1
app_name: go-app
base_image: registry.sandbox.monsoft.ru/murashov-1/task-1
tag: main
pullPolicy: IfNotPresent

deployment:
  container_port: 8080
  image_pull_secret_name: murashov-secret
service:
  type: ClusterIP
  port: 8080
  target_port: 8080

ingress:
  enabled: true
  host: "murashov-1.sandbox.monsoft.ru"
  path: /
  tls: []
  pathType: "Prefix"
  
config: |
  setting1: value1

secret:
  secure_var: "123"
